### ISSUE TITLE
waiting animation inside fancy folder..

### ISSUE THREAD

**Issue by pankajsingh92533** [Animeshz/scripts#9] opened 2023-10-22 13:23 UTC
i want to add waiting animation inside fancy folder.
Please assign me this issue under Hacktoberfest 2023 tag.

**Comment by Animeshz** [comment] 2023-10-22 19:11
Sure, go ahead :smile: :+1: 

Also this is duplicate of #1, so closing (and issue doesn't need assignment as this issue will be open for contributions in future as well).

**Closed by Animeshz** 2023-10-22 19:11 UTC
